'use client';

import * as React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { Download, FileText, Filter, Calendar, Search, FileSpreadsheet, FileJson, Loader2, FilePlus, Wand2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { DashboardContext } from '@/components/dashboard-client-extended';

export function ReportsView() {
    // Consume Global Reports State & Localization
    const { reports, setActiveView, t, language } = React.useContext(DashboardContext);

    const [searchQuery, setSearchQuery] = React.useState('');
    const [filterType, setFilterType] = React.useState<'ALL' | 'PDF' | 'CSV' | 'XLSX'>('ALL');
    const [downloadingId, setDownloadingId] = React.useState<string | null>(null);

    const { toast } = useToast();

    // Filter Logic
    const filteredReports = reports.filter(report => {
        const matchesSearch = report.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
            report.id.toLowerCase().includes(searchQuery.toLowerCase());
        const matchesType = filterType === 'ALL' || report.type === filterType;
        return matchesSearch && matchesType;
    });

    // Download Handler
    const handleDownload = (report: typeof reports[0]) => {
        setDownloadingId(report.id);

        setTimeout(() => {
            const content = `Report ID: ${report.id}\nName: ${report.name}\nDate: ${report.date}\nGenerated by Sentinel Dashbaord`;
            const blob = new Blob([content], { type: 'text/plain' });
            const url = window.URL.createObjectURL(blob);

            const a = document.createElement('a');
            a.href = url;
            a.download = `${report.name.replace(/\s+/g, '_')}.txt`;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);

            setDownloadingId(null);
            toast({
                title: language === 'ar' ? "تم التحميل" : "Download Complete",
                description: language === 'ar' ? `تم تحميل ${report.name} بنجاح` : `Successfully downloaded ${report.name}`,
            });
        }, 1500);
    };

    const getIconForType = (type: string) => {
        switch (type) {
            case 'PDF': return <FileText className="h-4 w-4 text-red-500" />;
            case 'CSV': return <FileSpreadsheet className="h-4 w-4 text-green-500" />;
            case 'XLSX': return <FileSpreadsheet className="h-4 w-4 text-green-600" />;
            case 'JSON': return <FileJson className="h-4 w-4 text-yellow-500" />;
            default: return <FileText className="h-4 w-4 text-muted-foreground" />;
        }
    };

    return (
        <div className="h-full overflow-y-auto p-6 space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h2 className="text-2xl font-bold tracking-tight">{t.reports}</h2>
                    <p className="text-muted-foreground">{language === 'ar' ? "الوصول وتحميل تقارير الاستخبارات." : "Access and download generated intelligence reports."}</p>
                </div>
                <div className="flex gap-2">
                    <Button variant="outline" size="sm">
                        <Calendar className="mr-2 h-4 w-4" />
                        {language === 'ar' ? "النطاق الزمني" : "Date Range"}
                    </Button>
                </div>
            </div>

            {/* Statistics Cards */}
            <div className="grid gap-4 md:grid-cols-4">
                <Card className="bg-primary/5 border-primary/10">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">{language === 'ar' ? "إجمالي التقارير" : "Total Reports"}</CardTitle>
                        <FileText className="h-4 w-4 text-primary" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{reports.length}</div>
                        <p className="text-xs text-muted-foreground">{language === 'ar' ? "تم إنشاؤها تلقائياً" : "Automatically generated"}</p>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">{language === 'ar' ? "مستندات PDF" : "PDF Documents"}</CardTitle>
                        <FileText className="h-4 w-4 text-red-500/70" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{reports.filter(r => r.type === 'PDF').length}</div>
                        <p className="text-xs text-muted-foreground">{language === 'ar' ? "ملخصات التحليل" : "Analysis Summaries"}</p>
                    </CardContent>
                </Card>
            </div>

            <Card className="min-h-[400px]">
                <CardHeader>
                    <div className="flex items-center justify-between">
                        <div>
                            <CardTitle>{language === 'ar' ? "التقارير المولدة" : "Generated Reports"}</CardTitle>
                            <CardDescription>{language === 'ar' ? "تصفح وإدارة أرشيف التقارير." : "Browse and manage your intelligence archives."}</CardDescription>
                        </div>
                        <div className="flex items-center gap-2">
                            {/* Search Input */}
                            <div className="relative w-64">
                                <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                                <Input
                                    placeholder={language === 'ar' ? "بحث في التقارير..." : "Search reports..."}
                                    className="pl-8"
                                    value={searchQuery}
                                    onChange={(e) => setSearchQuery(e.target.value)}
                                    disabled={reports.length === 0}
                                />
                            </div>

                            {/* Filter Dropdown */}
                            <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                    <Button variant="outline" size="icon" disabled={reports.length === 0}>
                                        <Filter className="h-4 w-4" />
                                    </Button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="end">
                                    <DropdownMenuLabel>{language === 'ar' ? "تصفية حسب النوع" : "Filter by Type"}</DropdownMenuLabel>
                                    <DropdownMenuSeparator />
                                    <DropdownMenuItem onClick={() => setFilterType('ALL')}>{language === 'ar' ? "الكل" : "All Types"}</DropdownMenuItem>
                                    <DropdownMenuItem onClick={() => setFilterType('PDF')}>PDF Documents</DropdownMenuItem>
                                    <DropdownMenuItem onClick={() => setFilterType('CSV')}>Data Exports (CSV)</DropdownMenuItem>
                                </DropdownMenuContent>
                            </DropdownMenu>
                        </div>
                    </div>
                </CardHeader>
                <CardContent>
                    {reports.length > 0 ? (
                        <div className="rounded-md border">
                            <Table>
                                <TableHeader>
                                    <TableRow>
                                        <TableHead className="text-left">{language === 'ar' ? "اسم التقرير" : "Report Name"}</TableHead>
                                        <TableHead>{language === 'ar' ? "التاريخ" : "Date"}</TableHead>
                                        <TableHead>{language === 'ar' ? "النوع" : "Type"}</TableHead>
                                        <TableHead>{language === 'ar' ? "الحجم" : "Size"}</TableHead>
                                        <TableHead>{language === 'ar' ? "الحالة" : "Status"}</TableHead>
                                        <TableHead className="text-right">{language === 'ar' ? "إجراء" : "Action"}</TableHead>
                                    </TableRow>
                                </TableHeader>
                                <TableBody>
                                    {filteredReports.length > 0 ? (
                                        filteredReports.map((report) => (
                                            <TableRow key={report.id}>
                                                <TableCell className="font-medium flex items-center gap-2">
                                                    {getIconForType(report.type)}
                                                    <div>
                                                        <div className="leading-none">{report.name}</div>
                                                        <div className="text-[10px] text-muted-foreground mt-1">{report.id}</div>
                                                    </div>
                                                </TableCell>
                                                <TableCell>{report.date}</TableCell>
                                                <TableCell>
                                                    <Badge variant="secondary" className="font-mono text-xs">{report.type}</Badge>
                                                </TableCell>
                                                <TableCell className="text-muted-foreground">{report.size}</TableCell>
                                                <TableCell>
                                                    <Badge
                                                        variant={report.status === 'Ready' ? 'outline' : 'secondary'}
                                                        className={report.status === 'Ready' ? 'bg-green-500/10 text-green-500 border-green-500/20' : ''}
                                                    >
                                                        {report.status}
                                                    </Badge>
                                                </TableCell>
                                                <TableCell className="text-right">
                                                    <Button
                                                        variant="ghost"
                                                        size="icon"
                                                        title="Download"
                                                        disabled={downloadingId === report.id}
                                                        onClick={() => handleDownload(report)}
                                                    >
                                                        {downloadingId === report.id ? (
                                                            <Loader2 className="h-4 w-4 animate-spin text-primary" />
                                                        ) : (
                                                            <Download className="h-4 w-4" />
                                                        )}
                                                    </Button>
                                                </TableCell>
                                            </TableRow>
                                        ))
                                    ) : (
                                        <TableRow>
                                            <TableCell colSpan={6} className="h-24 text-center">
                                                {language === 'ar' ? "لا توجد تقارير مطابقة." : "No reports found matching your search."}
                                            </TableCell>
                                        </TableRow>
                                    )}
                                </TableBody>
                            </Table>
                        </div>
                    ) : (
                        // EMPTY STATE FOR SYSTEM GEN REPORTS
                        <div className="flex flex-col items-center justify-center py-16 text-center border-2 border-dashed rounded-lg bg-muted/20">
                            <div className="p-4 rounded-full bg-muted mb-4 shadow-sm">
                                <Wand2 className="h-8 w-8 text-primary" />
                            </div>
                            <h3 className="text-lg font-semibold mb-2">{language === 'ar' ? "لم يتم إنشاء تقارير بعد" : "No system reports generated yet"}</h3>
                            <p className="text-sm text-muted-foreground max-w-sm mb-6">
                                {language === 'ar'
                                    ? "يتم إنشاء التقارير تلقائياً عند تشغيل تحليل جديد."
                                    : "Reports are automatically generated when you run an AI prediction."}
                                <br />
                                {language === 'ar' ? "اذهب إلى لوحة التحكم للبدء." : "Go to the Dashboard and run your first analysis."}
                            </p>
                            <Button onClick={() => setActiveView('dashboard')}>
                                {language === 'ar' ? "الذهاب للوحة التحكم" : "Go to Dashboard"}
                            </Button>
                        </div>
                    )}
                </CardContent>
            </Card>
        </div>
    );
}
